### ISSUE TITLE
Debian 8 plex error

### ISSUE THREAD

**Issue by mythcry** [QuickBox/QuickBox#1]
Can`t install plex on Debian8   3.16.0-4-amd64

It shows

● plexmediaserver.service - Plex Media Server for Linux
   Loaded: loaded (/lib/systemd/system/plexmediaserver.service; disabled)
   Active: activating (auto-restart) (Result: signal) since Mon 2017-02-13 21:49:22 CST; 1s ago
  Process: 2899 ExecStart=/bin/sh -c LD_LIBRARY_PATH=/usr/lib/plexmediaserver /usr/lib/plexmediaserver/Plex\ Media\ Server (code=killed, signal=ABRT)
  Process: 2895 ExecStartPre=/bin/sh -c /usr/bin/test -d "${PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR}" || /bin/mkdir -p "${PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR}" (code=exited, status=0/SUCCESS)
 Main PID: 2899 (code=killed, signal=ABRT)

**Comment by decompiled** [comment]
From the console uninstall Plex 'sudo box remove plex' then run 'sudo box install plex'.  For whatever reason the initial install doesn't create all the folders it needs to run and a reinstall works.  If your console gets stuck just during those commands just hit enter until you get your bash prompt back.
