### ISSUE TITLE
Public Trackers Conontribution

### ISSUE THREAD

**Issue by ADz-83** [QuickBox/QuickBox#2]
Adding these here as per instructions in hosts file.  This is a list what I currently use..

#Public_Trackers_Start
0.0.0.0 mgtracker.org
0.0.0.0 tracker.dler.org
0.0.0.0 inferno.demonoid.ph
0.0.0.0 tracker.aletorrenty.pl
0.0.0.0 tracker1.wasabii.com tracker2.wasabii.com tracker3.wasabii.com tracker4.wasabii.com
0.0.0.0 tracker.internetwarriors.net
0.0.0.0 pow7.com
0.0.0.0 t1.pow7.com
0.0.0.0 tracker.tntvillage.scambioetico.org
0.0.0.0 1.rarbg.me
0.0.0.0 2.rarbg.me
0.0.0.0 3.rarbg.me
0.0.0.0 4.rarbg.me
0.0.0.0 5.rarbg.me
0.0.0.0 6.rarbg.me
0.0.0.0 7.rarbg.me
0.0.0.0 8.rarbg.me
0.0.0.0 9.rarbg.me
0.0.0.0 p4p.arenabg.com
0.0.0.0 eddie4.nl
0.0.0.0 tracker.trackerfix.com
0.0.0.0 tracker.mg64.net
0.0.0.0 glotorrents.com
0.0.0.0 tracker.glotorrents.com
0.0.0.0 open.nyaatorrents.info
0.0.0.0 glotorrents.pw
0.0.0.0 tracker.publicbt.com
0.0.0.0 tracker.leechers-paradise.org
0.0.0.0 open.demonii.com
0.0.0.0 exodus.desync.com
0.0.0.0 tracker.openbittorrent.com
0.0.0.0 tracker.coppersurfer.tk
0.0.0.0 10.rarbg.com
0.0.0.0 11.rarbg.com
0.0.0.0 2006.sxsw.com
0.0.0.0 2007.sxsw.com
0.0.0.0 209.50.48.13
0.0.0.0 80.190.151.40
0.0.0.0 9.rarbg.com
0.0.0.0 9.rarbg.to
0.0.0.0 tracker.blackunicorn.xyz
0.0.0.0 tracker.aletorrenty.pl
0.0.0.0 torrent.gresille.org
0.0.0.0 tracker.opentrackr.org
0.0.0.0 p4p.arenabg.ch
0.0.0.0 tracker.pubt.net
0.0.0.0 tracker.aletorrenty.pl
0.0.0.0 94.75.205.147
0.0.0.0 a.scarywater.net
0.0.0.0 alanb.yi.org
0.0.0.0 all4nothin.net
0.0.0.0 anifans.ath.cx
0.0.0.0 animex.com
0.0.0.0 anstracker.no-ip.org
0.0.0.0 anstracker2.no-ip.org
0.0.0.0 anvilofsound.com
0.0.0.0 baka-updates.com
0.0.0.0 bakabt.com
0.0.0.0 bangladeshrocks.com
0.0.0.0 beta.legaltorrents.com
0.0.0.0 bittorrent.frozen-layer.net
0.0.0.0 borft.student.utwente.nl
0.0.0.0 bt-flux.com
0.0.0.0 bt.base0.net
0.0.0.0 bt.cartoonpalace.net
0.0.0.0 bt.eastgame.net
0.0.0.0 bt.edwardk.info
0.0.0.0 bt.emuparadise.org
0.0.0.0 bt.etree.org
0.0.0.0 bt.fansub-irc.org
0.0.0.0 bt.ktxp.com
0.0.0.0 bt.peerseed.com
0.0.0.0 bt.shinsen-subs.org
0.0.0.0 bt.speedsubs.org
0.0.0.0 bt.the9.com
0.0.0.0 bt.tjgame.enorth.com.cn
0.0.0.0 bt.ydy.com
0.0.0.0 btcomic.net
0.0.0.0 btjunkie.org
0.0.0.0 bttracker.acc.umu.se
0.0.0.0 colombo-bt.org
0.0.0.0 core-tracker.depthstrike.com
0.0.0.0 cotapers.org
0.0.0.0 coursetorrent.stanford.edu
0.0.0.0 crimsondays.com
0.0.0.0 csclub.uwaterloo.ca
0.0.0.0 dak180.dynalias.com
0.0.0.0 dattebayobrasil.com
0.0.0.0 deadacated.com
0.0.0.0 denis.stalker.h3q.com
0.0.0.0 dimeadozen.org
0.0.0.0 dnbtracker.org
0.0.0.0 doctortorrent.com
0.0.0.0 egelteek.no-ip.org
0.0.0.0 elsewhere.org
0.0.0.0 en.opensuse.org
0.0.0.0 euph.eu
0.0.0.0 ewheel.democracynow.org
0.0.0.0 exe64.com
0.0.0.0 exodus.1337x.org
0.0.0.0 extratorrent.com
0.0.0.0 extremebits.se
0.0.0.0 extremenova.org
0.0.0.0 eztv.tracker.prq.to
0.0.0.0 f.scarywater.net
0.0.0.0 fenopy.com
0.0.0.0 foobar2000.org
0.0.0.0 footage.stealthisfilm.com
0.0.0.0 gdbt.3322.org
0.0.0.0 h33t.com
0.0.0.0 handfilms.com
0.0.0.0 harryy.us
0.0.0.0 hd-dream.net
0.0.0.0 hewgill.com
0.0.0.0 hexagon.cc
0.0.0.0 hits4.us
0.0.0.0 hypaculture.com
0.0.0.0 indytorrents.org
0.0.0.0 inferno.demonoid.com
0.0.0.0 insanity.in
0.0.0.0 irrenhaus.dyndns.dk
0.0.0.0 islamictorrents.net
0.0.0.0 isohunt.com
0.0.0.0 itpb.tracker.prq.to
0.0.0.0 jem.d-addicts.com
0.0.0.0 jem.d-addicts.net
0.0.0.0 kaa.animeconnection.net
0.0.0.0 kaoz-subs.de
0.0.0.0 linuxtracker.org
0.0.0.0 livetorrents.com
0.0.0.0 mass-torrent.com
0.0.0.0 mightynova.com
0.0.0.0 monova.org
0.0.0.0 mozilla.isohunt.com
0.0.0.0 mrtwig.net
0.0.0.0 music-video-torrents.afz.biz
0.0.0.0 mw.igg.com
0.0.0.0 nanikano.no-ip.org
0.0.0.0 nemesis.1337x.org
0.0.0.0 newvoyages.us
0.0.0.0 nova9.org
0.0.0.0 nrkbeta.no
0.0.0.0 nxtgn.org
0.0.0.0 nyaatorrent.info
0.0.0.0 nyaatorrent.org
0.0.0.0 nyaatorrents.info
0.0.0.0 nyaatorrents.org
0.0.0.0 onebigtorrent.org
0.0.0.0 os.us.to
0.0.0.0 ostorr.org
0.0.0.0 p2p.lineage2.com.cn
0.0.0.0 petrochemical-services.com
0.0.0.0 photodiode.mine.nu
0.0.0.0 pj.sidewalkcrusaders.com
0.0.0.0 pleasuredome.org.uk
0.0.0.0 podtropolis.com
0.0.0.0 publicbt.com
0.0.0.0 publiclibrary.metamute.org
0.0.0.0 quetooter-torrents.kicks-ass.net
0.0.0.0 radioarchive.cc
0.0.0.0 randomnothings.com
0.0.0.0 rbgi.net
0.0.0.0 rebootedc.no-ip.org
0.0.0.0 redsphereglobal.com
0.0.0.0 revision3.com
0.0.0.0 rockbox.psychocydd.co.uk
0.0.0.0 rocketredrockers.net
0.0.0.0 saiei.edwardk.info
0.0.0.0 seedler.org
0.0.0.0 seedpeer.com
0.0.0.0 server2.deadacated.com
0.0.0.0 shadowshq.yi.org
0.0.0.0 share.dmhy.org
0.0.0.0 sharereactor.com
0.0.0.0 sharetv.org
0.0.0.0 snowy.arsc.alaska.edu
0.0.0.0 sombarato.org
0.0.0.0 suprnova.org
0.0.0.0 team-mkv.homedns.org
0.0.0.0 thepiratebay.org
0.0.0.0 thewirdsdomain.com
0.0.0.0 tk.btcomic.net
0.0.0.0 tk.comican.com
0.0.0.0 tlm-project.org
0.0.0.0 tntvillage.org
0.0.0.0 tog.net
0.0.0.0 tokyotosho.com
0.0.0.0 top.igg.com
0.0.0.0 torrent-download.to
0.0.0.0 torrent-downloads.to
0.0.0.0 torrent.fedoraproject.org
0.0.0.0 torrent.ibiblio.org
0.0.0.0 torrent.ipnm.ru
0.0.0.0 torrent.mandriva.com
0.0.0.0 torrent.unix-ag.uni-kl.de
0.0.0.0 torrentat.org
0.0.0.0 torrentbytes.net
0.0.0.0 torrentchannel.com
0.0.0.0 torrentraider.com
0.0.0.0 torrentreactor.net
0.0.0.0 torrentriot.net
0.0.0.0 torrents.freebsd.org
0.0.0.0 torrents.gentoo.org
0.0.0.0 torrents.jamendo.com
0.0.0.0 torrents.red.com
0.0.0.0 torrents.vugames.com
0.0.0.0 torrentsforall.net
0.0.0.0 torrentspy.com
0.0.0.0 torrentzilla.org
0.0.0.0 torrentzone.net
0.0.0.0 tracker.anime-4ever.org
0.0.0.0 tracker.anime-kraze.org
0.0.0.0 tracker.anirena.com
0.0.0.0 tracker.bitreactor.to
0.0.0.0 tracker.bootytorrents.com
0.0.0.0 tracker.denness.net
0.0.0.0 tracker.frozen-layer.net
0.0.0.0 tracker.gits-fans.com
0.0.0.0 tracker.gotwoot.net
0.0.0.0 tracker.ilibr.org
0.0.0.0 tracker.ilovetorrents.com
0.0.0.0 tracker.istole.it
0.0.0.0 tracker.mariposahd.tv
0.0.0.0 tracker.minglong.org
0.0.0.0 tracker.openbittorrent.com
0.0.0.0 tracker.real-3d-games.com
0.0.0.0 tracker.seeding.it
0.0.0.0 tracker.tahise.info
0.0.0.0 tracker.tlm-project.org
0.0.0.0 tracker.to
0.0.0.0 tracker.token.ro
0.0.0.0 tracker.torrent.to
0.0.0.0 tracker.torrent411.com
0.0.0.0 tracker.torrentbay.to
0.0.0.0 tracker.torrentbox.com
0.0.0.0 tracker.torrenty.org
0.0.0.0 tracker.zaerc.com
0.0.0.0 tracker1.comicpirates.info
0.0.0.0 tracker1.finalgear.com
0.0.0.0 tracker1.torrentum.pl
0.0.0.0 tracker1.transamrit.net
0.0.0.0 tracker2.comicpirates.info
0.0.0.0 tracker2.finalgear.com
0.0.0.0 tracker2.torrentum.pl
0.0.0.0 tracker3.comicpirates.info
0.0.0.0 tracker3.finalgear.com
0.0.0.0 tracker4.finalgear.com
0.0.0.0 tracker5.zcultfm.com
0.0.0.0 trackerb.zcultfm.com
0.0.0.0 trackers.transamrit.net
0.0.0.0 transamrit.net
0.0.0.0 tvrss.net
0.0.0.0 ushiai.no-ip.org
0.0.0.0 usotsuki.info
0.0.0.0 weebl00.nl
0.0.0.0 weedy.1.vg
0.0.0.0 wiesneronline.net
0.0.0.0 wrentype.hoshinet.org
0.0.0.0 www.2torrent.com
0.0.0.0 www.ahashare.com
0.0.0.0 www.allotracker.com
0.0.0.0 www.animeindex.net
0.0.0.0 www.animesuki.com
0.0.0.0 www.bitenova.nl
0.0.0.0 www.bittorrent.am
0.0.0.0 www.bittorrent.com
0.0.0.0 www.bittorrentshare.com
0.0.0.0 www.bt-chat.com
0.0.0.0 www.btmon.com
0.0.0.0 www.btscene.com
0.0.0.0 www.btswarm.org
0.0.0.0 www.chinadocumentaries.com
0.0.0.0 www.chomskytorrents.org
0.0.0.0 www.d-addicts.com
0.0.0.0 www.datorrents.com
0.0.0.0 www.dattebayo.com
0.0.0.0 www.deadfrog.us
0.0.0.0 www.demonoid.com
0.0.0.0 www.downloadanime.org
0.0.0.0 www.elephantsdream.org
0.0.0.0 www.eztv.it
0.0.0.0 www.freelegaltorrents.com
0.0.0.0 www.fulldls.com
0.0.0.0 www.gameupdates.org
0.0.0.0 www.gotwoot.net
0.0.0.0 www.greylodge.org
0.0.0.0 www.harveydanger.com
0.0.0.0 www.hightorrent.to
0.0.0.0 www.idealtorrent.com
0.0.0.0 www.ipodnova.tv
0.0.0.0 www.jamendo.com
0.0.0.0 www.legittorrents.info
0.0.0.0 www.livingtorrents.com
0.0.0.0 www.mabula.net
0.0.0.0 www.mac-torrents.com
0.0.0.0 www.matrix8.com
0.0.0.0 www.mininova.org
0.0.0.0 www.mvgroup.org
0.0.0.0 www.mvtorrents.com
0.0.0.0 www.mybittorrent.com
0.0.0.0 www.mytorrent.pl
0.0.0.0 www.new2me.net
0.0.0.0 www.newtorrents.info
0.0.0.0 www.nitcom.com.au
0.0.0.0 www.okbt.com
0.0.0.0 www.opensource-cms.org
0.0.0.0 www.opera.com
0.0.0.0 www.p2pbg.com
0.0.0.0 www.peteteo.com
0.0.0.0 www.pimptorrent.com
0.0.0.0 www.point-blank.cc
0.0.0.0 www.psppirates.com
0.0.0.0 www.publicdomaintorrents.com
0.0.0.0 www.raphustle.com
0.0.0.0 www.seedleech.com
0.0.0.0 www.sitasingstheblues.com
0.0.0.0 www.slackware.com
0.0.0.0 www.slotorrent.net
0.0.0.0 www.smaragdtorrent.to
0.0.0.0 www.solidz.com
0.0.0.0 www.speedtorrent.to
0.0.0.0 www.starwreck.com
0.0.0.0 www.sumotorrent.com
0.0.0.0 www.superfundo.org
0.0.0.0 www.thehawks.org
0.0.0.0 www.thetorrentsite.com
0.0.0.0 www.todotorrents.com
0.0.0.0 www.torrent.to
0.0.0.0 www.torrentbar.com
0.0.0.0 www.torrentbox.com
0.0.0.0 www.torrentdownloads.net
0.0.0.0 www.torrentlocomotive.com
0.0.0.0 www.torrentportal.com
0.0.0.0 www.torrentreactor.to
0.0.0.0 www.torrentum.pl
0.0.0.0 www.tracker.big-torrent.to
0.0.0.0 www.tribalmixes.com
0.0.0.0 www.tuxdistro.com
0.0.0.0 www.tvnihon.com
0.0.0.0 www.vuze.com
0.0.0.0 www.web-torrent.com
0.0.0.0 www.worldnova.org
0.0.0.0 www.zeoez.com
0.0.0.0 www.zoektorrents.com
0.0.0.0 xabin.mine.nu
0.0.0.0 xbox.udp.at
0.0.0.0 yhbt.mine.nu
0.0.0.0 zerowing.idsoftware.com
0.0.0.0 zorgtorrent.com
0.0.0.0 open.nyaatorrents.info
0.0.0.0 open.nyaatorrents.info:6544
0.0.0.0 nyaa.se
0.0.0.0 retracker.krs-ix.ru
0.0.0.0 tracker.sktorrent.net
0.0.0.0 wareztorrent.com
0.0.0.0 atrack.pow7.com
0.0.0.0 tracker.dutchtracking.nl
0.0.0.0 tracker.ex.ua
0.0.0.0 retracker.krs-ix.ru
0.0.0.0 tracker.glotorrents.com
0.0.0.0 tracker.flashtorrents.org
0.0.0.0 explodie.org:6969
0.0.0.0 tracker1.wasabii.com.tw:6969
0.0.0.0 tracker1.wasabii.com.tw
0.0.0.0 thetracker.org
0.0.0.0 retracker.krs-ix.ru
0.0.0.0 open.acgtracker.com
0.0.0.0 open.acgtracker.com:1096
0.0.0.0 open.acgtracker.com:1096/announce
0.0.0.0 explodie.org
0.0.0.0 tracker.baravik.org:6970
0.0.0.0 tracker.baravik.org
0.0.0.0 open.nyaatorrents.info:6544
0.0.0.0 open.nyaatorrents.info
0.0.0.0 tracker.trackerfix.com:80
0.0.0.0 tracker.trackerfix.com
0.0.0.0 tracker.tfile.me
0.0.0.0 mgtracker.org:2710
0.0.0.0 mgtracker.org
0.0.0.0 tracker.piratepublic.com
0.0.0.0 zer0day.ch
0.0.0.0 tracker.zer0day.to
0.0.0.0 zer0day.to
0.0.0.0 explodie.org
#Public_Trackers_End

**Comment by JMSDOnline** [comment]
Thank you for contributing your list @ADz-83. We'll have this pushed to the next update.

**Comment by ADz-83** [comment]
@JMSDOnline   You're welcome bud.  Thanks for providing such a great project.   I've updated and also sorted my list since posting this.  Here is new version for you.  


#Public_Trackers_Start
0.0.0.0 109.235.50.166
0.0.0.0 1.rarbg.me
0.0.0.0 10.rarbg.com
0.0.0.0 109.235.50.166
0.0.0.0 11.rarbg.com
0.0.0.0 125.227.35.196
0.0.0.0 2.rarbg.me
0.0.0.0 2006.sxsw.com
0.0.0.0 2007.sxsw.com
0.0.0.0 209.50.48.13
0.0.0.0 210.244.71.25
0.0.0.0 210.244.71.25:6969
0.0.0.0 3.rarbg.me
0.0.0.0 4.rarbg.me
0.0.0.0 46.4.109.148
0.0.0.0 46.4.109.148:6969
0.0.0.0 5.rarbg.me
0.0.0.0 6.rarbg.me
0.0.0.0 62.138.0.158
0.0.0.0 7.rarbg.me
0.0.0.0 8.rarbg.me
0.0.0.0 80.190.151.40
0.0.0.0 87.248.186.252
0.0.0.0 87.248.186.252:8080
0.0.0.0 9.rarbg.com
0.0.0.0 9.rarbg.me
0.0.0.0 9.rarbg.to
0.0.0.0 94.23.183.33
0.0.0.0 94.75.205.147
0.0.0.0 a.scarywater.net
0.0.0.0 alanb.yi.org
0.0.0.0 all4nothin.net
0.0.0.0 anifans.ath.cx
0.0.0.0 animex.com
0.0.0.0 anstracker.no-ip.org
0.0.0.0 anstracker2.no-ip.org
0.0.0.0 anvilofsound.com
0.0.0.0 atrack.pow7.com
0.0.0.0 baka-updates.com
0.0.0.0 bakabt.com
0.0.0.0 bangladeshrocks.com
0.0.0.0 beta.legaltorrents.com
0.0.0.0 bittorrent.frozen-layer.net
0.0.0.0 borft.student.utwente.nl
0.0.0.0 bt-flux.com
0.0.0.0 bt.base0.net
0.0.0.0 bt.cartoonpalace.net
0.0.0.0 bt.eastgame.net
0.0.0.0 bt.edwardk.info
0.0.0.0 bt.emuparadise.org
0.0.0.0 bt.etree.org
0.0.0.0 bt.fansub-irc.org
0.0.0.0 bt.ktxp.com
0.0.0.0 bt.peerseed.com
0.0.0.0 bt.shinsen-subs.org
0.0.0.0 bt.speedsubs.org
0.0.0.0 bt.the9.com
0.0.0.0 bt.tjgame.enorth.com
0.0.0.0 bt.tjgame.enorth.com.cn
0.0.0.0 bt.ydy.com
0.0.0.0 btcomic.net
0.0.0.0 btjunkie.org
0.0.0.0 bttracker.acc.umu.se
0.0.0.0 colombo-bt.org
0.0.0.0 core-tracker.depthstrike.com
0.0.0.0 cotapers.org
0.0.0.0 coursetorrent.stanford.edu
0.0.0.0 crimsondays.com
0.0.0.0 csclub.uwaterloo.ca
0.0.0.0 dak180.dynalias.com
0.0.0.0 dattebayobrasil.com
0.0.0.0 deadacated.com
0.0.0.0 denis.stalker.h3q.com
0.0.0.0 dimeadozen.org
0.0.0.0 dnbtracker.org
0.0.0.0 doctortorrent.com
0.0.0.0 eddie4.nl
0.0.0.0 egelteek.no-ip.org
0.0.0.0 elsewhere.org
0.0.0.0 en.opensuse.org
0.0.0.0 euph.eu
0.0.0.0 ewheel.democracynow.org
0.0.0.0 exe64.com
0.0.0.0 exodus.1337x.org
0.0.0.0 exodus.desync.com
0.0.0.0 explodie.org
0.0.0.0 explodie.org:6969
0.0.0.0 extratorrent.com
0.0.0.0 extremebits.se
0.0.0.0 extremenova.org
0.0.0.0 eztv.tracker.prq.to
0.0.0.0 f.scarywater.net
0.0.0.0 fenopy.com
0.0.0.0 foobar2000.org
0.0.0.0 footage.stealthisfilm.com
0.0.0.0 gdbt.3322.org
0.0.0.0 glotorrents.com
0.0.0.0 glotorrents.pw
0.0.0.0 h33t.com
0.0.0.0 handfilms.com
0.0.0.0 harryy.us
0.0.0.0 hd-dream.net
0.0.0.0 hewgill.com
0.0.0.0 hexagon.cc
0.0.0.0 hits4.us
0.0.0.0 hypaculture.com
0.0.0.0 i.bandito.org
0.0.0.0 indytorrents.org
0.0.0.0 inferno.demonoid.com
0.0.0.0 inferno.demonoid.ph
0.0.0.0 insanity.in
0.0.0.0 ipv4.tracker.harry.lu
0.0.0.0 irrenhaus.dyndns.dk
0.0.0.0 islamictorrents.net
0.0.0.0 isohunt.com
0.0.0.0 itpb.tracker.prq.to
0.0.0.0 jem.d-addicts.com
0.0.0.0 jem.d-addicts.net
0.0.0.0 kaa.animeconnection.net
0.0.0.0 kaoz-subs.de
0.0.0.0 linuxtracker.org
0.0.0.0 livetorrents.com
0.0.0.0 mass-torrent.com
0.0.0.0 mgtracker.org
0.0.0.0 mgtracker.org:2710
0.0.0.0 mightynova.com
0.0.0.0 monova.org
0.0.0.0 mozilla.isohunt.com
0.0.0.0 mrtwig.net
0.0.0.0 music-video-torrents.afz.biz
0.0.0.0 mw.igg.com
0.0.0.0 nanikano.no-ip.org
0.0.0.0 nemesis.1337x.org
0.0.0.0 newvoyages.us
0.0.0.0 nova9.org
0.0.0.0 nrkbeta.no
0.0.0.0 nxtgn.org
0.0.0.0 nyaa.se
0.0.0.0 nyaatorrent.info
0.0.0.0 nyaatorrent.org
0.0.0.0 nyaatorrents.info
0.0.0.0 nyaatorrents.org
0.0.0.0 onebigtorrent.org
0.0.0.0 open.acgtracker.com
0.0.0.0 open.acgtracker.com:1096
0.0.0.0 open.acgtracker.com:1096/announce
0.0.0.0 open.demonii.com
0.0.0.0 open.nyaatorrents.info
0.0.0.0 open.nyaatorrents.info:6544
0.0.0.0 open.stealth.si
0.0.0.0 openbittorrent.com
0.0.0.0 os.us.to
0.0.0.0 ostorr.org
0.0.0.0 p2p.lineage2.com.cn
0.0.0.0 p4p.arenabg.ch
0.0.0.0 p4p.arenabg.com
0.0.0.0 petrochemical-services.com
0.0.0.0 photodiode.mine.nu
0.0.0.0 pj.sidewalkcrusaders.com
0.0.0.0 pleasuredome.org
0.0.0.0 pleasuredome.org.uk
0.0.0.0 podtropolis.com
0.0.0.0 pow7.com
0.0.0.0 publicbt.com
0.0.0.0 publiclibrary.metamute.org
0.0.0.0 quetooter-torrents.kicks-ass.net
0.0.0.0 radioarchive.cc
0.0.0.0 randomnothings.com
0.0.0.0 rbgi.net
0.0.0.0 rebootedc.no-ip.org
0.0.0.0 redsphereglobal.com
0.0.0.0 retracker.krs-ix.ru
0.0.0.0 revision3.com
0.0.0.0 rockbox.psychocydd.co.uk
0.0.0.0 rocketredrockers.net
0.0.0.0 saiei.edwardk.info
0.0.0.0 seedler.org
0.0.0.0 seedpeer.com
0.0.0.0 server2.deadacated.com
0.0.0.0 shadowshq.yi.org
0.0.0.0 share.dmhy.org
0.0.0.0 sharereactor.com
0.0.0.0 sharetv.org
0.0.0.0 shubt.net
0.0.0.0 snowy.arsc.alaska.edu
0.0.0.0 sombarato.org
0.0.0.0 suprnova.org
0.0.0.0 t1.pow7.com
0.0.0.0 team-mkv.homedns.org
0.0.0.0 thepiratebay.org
0.0.0.0 thetracker.org
0.0.0.0 thewirdsdomain.com
0.0.0.0 tk.btcomic.net
0.0.0.0 tk.comican.com
0.0.0.0 tlm-project.org
0.0.0.0 tntvillage.org
0.0.0.0 tog.net
0.0.0.0 tokyotosho.com
0.0.0.0 top.igg.com
0.0.0.0 torrent-download.to
0.0.0.0 torrent-downloads.to
0.0.0.0 torrent.fedoraproject.org
0.0.0.0 torrent.gresille.org
0.0.0.0 torrent.ibiblio.org
0.0.0.0 torrent.ipnm.ru
0.0.0.0 torrent.mandriva.com
0.0.0.0 torrent.unix-ag.uni-kl.de
0.0.0.0 torrentat.org
0.0.0.0 torrentbytes.net
0.0.0.0 torrentchannel.com
0.0.0.0 torrentraider.com
0.0.0.0 torrentreactor.net
0.0.0.0 torrentriot.net
0.0.0.0 torrents.freebsd.org
0.0.0.0 torrents.gentoo.org
0.0.0.0 torrents.jamendo.com
0.0.0.0 torrents.red.com
0.0.0.0 torrents.vugames.com
0.0.0.0 torrentsforall.net
0.0.0.0 torrentspy.com
0.0.0.0 torrentzilla.org
0.0.0.0 torrentzone.net
0.0.0.0 tracker.aletorrenty.pl
0.0.0.0 tracker.anime-4ever.org
0.0.0.0 tracker.anime-kraze.org
0.0.0.0 tracker.anirena.com
0.0.0.0 tracker.baravik.org
0.0.0.0 tracker.baravik.org:6970
0.0.0.0 tracker.bitreactor.to
0.0.0.0 tracker.blackunicorn.xyz
0.0.0.0 tracker.bootytorrents.com
0.0.0.0 tracker.coppersurfer.tk
0.0.0.0 tracker.denness.net
0.0.0.0 tracker.dler.org
0.0.0.0 tracker.dutchtracking.nl
0.0.0.0 tracker.ex.ua
0.0.0.0 tracker.exdesi.com
0.0.0.0 tracker.filetracker.pl
0.0.0.0 tracker.flashtorrents.org
0.0.0.0 tracker.frozen-layer.net
0.0.0.0 tracker.gits-fans.com
0.0.0.0 tracker.glotorrents.com
0.0.0.0 tracker.gotwoot.net
0.0.0.0 tracker.grepler.com
0.0.0.0 tracker.ilibr.org
0.0.0.0 tracker.ilovetorrents.com
0.0.0.0 tracker.internetwarriors.net
0.0.0.0 tracker.istole.it
0.0.0.0 tracker.leechers-paradise.org
0.0.0.0 tracker.mariposahd.tv
0.0.0.0 tracker.mg64.net
0.0.0.0 tracker.minglong.org
0.0.0.0 tracker.openbittorrent.com
0.0.0.0 tracker.opentrackr.org
0.0.0.0 tracker.piratepublic.com
0.0.0.0 tracker.prq.to
0.0.0.0 tracker.publicbt.com
0.0.0.0 tracker.pubt.net
0.0.0.0 tracker.real-3d-games.com
0.0.0.0 tracker.se
0.0.0.0 tracker.seeding.it
0.0.0.0 tracker.sktorrent.net
0.0.0.0 tracker.tahise.info
0.0.0.0 tracker.tfile.me
0.0.0.0 tracker.tiny-vps.com
0.0.0.0 tracker.tlm-project.org
0.0.0.0 tracker.tntvillage.scambioetico.org
0.0.0.0 tracker.to
0.0.0.0 tracker.token.ro
0.0.0.0 tracker.torrent.to
0.0.0.0 tracker.torrent411.com
0.0.0.0 tracker.torrentbay.to
0.0.0.0 tracker.torrentbox.com
0.0.0.0 tracker.torrenty.org
0.0.0.0 tracker.trackerfix.com
0.0.0.0 tracker.trackerfix.com:80
0.0.0.0 tracker.zaerc.com
0.0.0.0 tracker.zer0day.to
0.0.0.0 tracker1.comicpirates.info
0.0.0.0 tracker1.finalgear.com
0.0.0.0 tracker1.torrentum.pl
0.0.0.0 tracker1.transamrit.net
0.0.0.0 tracker1.wasabii.com tracker2.wasabii.com tracker3.wasabii.com tracker4.wasabii.com
0.0.0.0 tracker1.wasabii.com.tw
0.0.0.0 tracker1.wasabii.com.tw:6969
0.0.0.0 tracker2.comicpirates.info
0.0.0.0 tracker2.finalgear.com
0.0.0.0 tracker2.torrentum.pl
0.0.0.0 tracker2.wasabii.com.tw
0.0.0.0 tracker3.comicpirates.info
0.0.0.0 tracker3.finalgear.com
0.0.0.0 tracker4.finalgear.com
0.0.0.0 tracker5.zcultfm.com
0.0.0.0 trackerb.zcultfm.com
0.0.0.0 trackers.transamrit.net
0.0.0.0 transamrit.net
0.0.0.0 tvrss.net
0.0.0.0 ushiai.no-ip.org
0.0.0.0 usotsuki.info
0.0.0.0 wareztorrent.com
0.0.0.0 weebl00.nl
0.0.0.0 weedy.1.vg
0.0.0.0 wiesneronline.net
0.0.0.0 wrentype.hoshinet.org
0.0.0.0 www.2torrent.com
0.0.0.0 www.ahashare.com
0.0.0.0 www.allotracker.com
0.0.0.0 www.animeindex.net
0.0.0.0 www.animesuki.com
0.0.0.0 www.bitenova.nl
0.0.0.0 www.bittorrent.am
0.0.0.0 www.bittorrent.com
0.0.0.0 www.bittorrentshare.com
0.0.0.0 www.bt-chat.com
0.0.0.0 www.btmon.com
0.0.0.0 www.btscene.com
0.0.0.0 www.btswarm.org
0.0.0.0 www.chinadocumentaries.com
0.0.0.0 www.chomskytorrents.org
0.0.0.0 www.d-addicts.com
0.0.0.0 www.datorrents.com
0.0.0.0 www.dattebayo.com
0.0.0.0 www.deadfrog.us
0.0.0.0 www.demonoid.com
0.0.0.0 www.downloadanime.org
0.0.0.0 www.elephantsdream.org
0.0.0.0 www.eztv.it
0.0.0.0 www.freelegaltorrents.com
0.0.0.0 www.fulldls.com
0.0.0.0 www.gameupdates.org
0.0.0.0 www.gotwoot.net
0.0.0.0 www.greylodge.org
0.0.0.0 www.harveydanger.com
0.0.0.0 www.hightorrent.to
0.0.0.0 www.idealtorrent.com
0.0.0.0 www.ipodnova.tv
0.0.0.0 www.jamendo.com
0.0.0.0 www.legittorrents.info
0.0.0.0 www.livingtorrents.com
0.0.0.0 www.mabula.net
0.0.0.0 www.mac-torrents.com
0.0.0.0 www.matrix8.com
0.0.0.0 www.mininova.org
0.0.0.0 www.mvgroup.org
0.0.0.0 www.mvtorrents.com
0.0.0.0 www.mybittorrent.com
0.0.0.0 www.mytorrent.pl
0.0.0.0 www.new2me.net
0.0.0.0 www.newtorrents.info
0.0.0.0 www.nitcom.com.au
0.0.0.0 www.okbt.com
0.0.0.0 www.opensource-cms.org
0.0.0.0 www.opera.com
0.0.0.0 www.p2pbg.com
0.0.0.0 www.peteteo.com
0.0.0.0 www.pimptorrent.com
0.0.0.0 www.point-blank.cc
0.0.0.0 www.psppirates.com
0.0.0.0 www.publicdomaintorrents.com
0.0.0.0 www.raphustle.com
0.0.0.0 www.seedleech.com
0.0.0.0 www.sitasingstheblues.com
0.0.0.0 www.slackware.com
0.0.0.0 www.slotorrent.net
0.0.0.0 www.smaragdtorrent.to
0.0.0.0 www.solidz.com
0.0.0.0 www.speedtorrent.to
0.0.0.0 www.starwreck.com
0.0.0.0 www.sumotorrent.com
0.0.0.0 www.superfundo.org
0.0.0.0 www.thehawks.org
0.0.0.0 www.thetorrentsite.com
0.0.0.0 www.todotorrents.com
0.0.0.0 www.torrent.to
0.0.0.0 www.torrentbar.com
0.0.0.0 www.torrentbox.com
0.0.0.0 www.torrentdownloads.net
0.0.0.0 www.torrentlocomotive.com
0.0.0.0 www.torrentportal.com
0.0.0.0 www.torrentreactor.to
0.0.0.0 www.torrentum.pl
0.0.0.0 www.tracker.big-torrent.to
0.0.0.0 www.tribalmixes.com
0.0.0.0 www.tuxdistro.com
0.0.0.0 www.tvnihon.com
0.0.0.0 www.vuze.com
0.0.0.0 www.web-torrent.com
0.0.0.0 www.worldnova.org
0.0.0.0 www.zeoez.com
0.0.0.0 www.zoektorrents.com
0.0.0.0 xabin.mine.nu
0.0.0.0 xbox.udp.at
0.0.0.0 yhbt.mine.nu
0.0.0.0 zer0day.ch
0.0.0.0 zer0day.to
0.0.0.0 zerowing.idsoftware.com
0.0.0.0 zorgtorrent.com
#Public_Trackers_End
