### ISSUE TITLE
Debian 8 won`t work

### ISSUE THREAD

**Issue by mythcry** [QuickBox/QuickBox#3]
Pulling QuickBox Ecosystem ... [ DONE ]
Updating system ...  [|]  cp: cannot stat ‘/etc/QuickBox/setup/templates/apt.sources/debian.template’: No such file or directory                                                                                      [ DONE ]
Installing all needed dependencies ... [ DONE ]
Setting up system executables ...  [|]  cp: cannot stat ‘/etc/QuickBox/packages//.’: No such file or directory
cp: cannot stat ‘/usr/local/bin/quickbox/system/reload’: No such file or directory                      [ DONE ]
Building required user directories ...  [|]  cp: cannot stat ‘/etc/QuickBox/setup/templates/skel/.’: No such file or directory
tar (child): /etc/QuickBox/setup/sources/rarlinux-x64-5.3.0.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
cp: cannot stat ‘./rar/*rar’: No such file or directory
cp: cannot stat ‘./rar/*rar’: No such file or directory                                                 [ DONE ]
Setting up Limited Shell environment ...  [-]  cp: cannot stat ‘/etc/QuickBox/setup/templates/lshell.conf.template’: No such file or directory                                                                        [ DONE ]
Building ffmpeg from source for screenshots ... [ DONE ]
cp: cannot stat ‘/etc/QuickBox/setup/templates/sudoers.template’: No such file or directory
awk: cannot open /etc/sudoers (No such file or directory)
/root/QuickBox/setup/quickbox-setup: line 562: /etc/apache2/master.txt: No such file or directory
Installing xmlrpc-c-1.33.12 ...  [|]  cp: cannot stat ‘/etc/QuickBox/setup/sources/xmlrpc-c_1-33-12/’: No such file or directory
/root/QuickBox/setup/quickbox-setup: line 573: cd: xmlrpc-c_1-33-12: No such file or directory
chmod: cannot access ‘configure’: No such file or directory
chmod: cannot access ‘install-sh’: No such file or directory                                            [ DONE ]
Installing libtorrent-0.13.4 ...  [|]  cp: cannot stat ‘/etc/QuickBox/setup/sources/libtorrent-0.13.4.tar.gz’: No such file or directory
/root/QuickBox/setup/quickbox-setup: line 590: cd: libtorrent-0.13.4: No such file or directory         [ DONE ]
Installing rtorrent-0.9.4 ...  [|]  cp: cannot stat ‘/etc/QuickBox/setup/sources/rtorrent-0.9.4.tar.gz’: No such file or directory
/root/QuickBox/setup/quickbox-setup: line 606: cd: rtorrent-0.9.4: No such file or directory            [ DONE ]
Installing rutorrent into /srv ...  [|]  cp: cannot stat ‘/etc/QuickBox/rutorrent//.’: No such file or directory                                                                                                      [ DONE ]
Installing rutorrent plugins ... cp: cannot stat ‘/etc/QuickBox/rtplugins//.’: No such file or directory
[ DONE ]
Installing deluge ...  [/]  python: can't open file '/etc/QuickBox/packages//system/deluge.Userpass.py': [Errno 2] No such file or directory
python: can't open file '/etc/QuickBox/packages//system/deluge.addHost.py': [Errno 2] No such file or directory                                                                                                        [-]  cp: cannot stat ‘/etc/QuickBox/setup/templates/core.conf.template’: No such file or directory
cp: cannot stat ‘/etc/QuickBox/setup/templates/web.conf.template’: No such file or directory
cp: cannot stat ‘/etc/QuickBox/setup/templates/hostlist.conf.1.2.template’: No such file or directory
sed: can't read /home/mythcry/.config/deluge/core.conf: No such file or directory
sed: can't read /home/mythcry/.config/deluge/core.conf: No such file or directory
sed: can't read /home/mythcry/.config/deluge/core.conf: No such file or directory
sed: can't read /home/mythcry/.config/deluge/web.conf: No such file or directory
sed: can't read /home/mythcry/.config/deluge/web.conf: No such file or directory
sed: can't read /home/mythcry/.config/deluge/web.conf: No such file or directory
sed: can't read /home/mythcry/.config/deluge/hostlist.conf.1.2: No such file or directory
sed: can't read /home/mythcry/.config/deluge/hostlist.conf.1.2: No such file or directory
sed: can't read /home/mythcry/.config/deluge/hostlist.conf.1.2: No such file or directory
sed: can't read /home/mythcry/.config/deluge/hostlist.conf.1.2: No such file or directory               [ DONE ]
Installing mktorrent from source ...  [\]  /root/QuickBox/setup/quickbox-setup: line 703: cd: mktorrent-1.1: No such file or directory                                                                                [ DONE ]
Installing quickbox dashboard ... cp: cannot stat ‘/etc/QuickBox/dashboard//.’: No such file or directory
touch: cannot touch ‘/srv/rutorrent/home/db/output.log’: No such file or directory
[ DONE ]
Setting up seedbox.conf for apache ... cp: cannot stat ‘/etc/QuickBox/setup/templates/aliases-seedbox.conf.template’: No such file or directory
sed: can't read /etc/apache2/sites-enabled/aliases-seedbox.conf: No such file or directory
 [|]  cp: cannot stat ‘/etc/QuickBox/setup/templates/default-ssl.conf.template’: No such file or directory
sed: can't read /etc/apache2/sites-enabled/default-ssl.conf: No such file or directory
sed: can't read /etc/apache2/sites-enabled/default-ssl.conf: No such file or directory
sed: can't read /etc/apache2/sites-enabled/default-ssl.conf: No such file or directory
sed: can't read /etc/apache2/sites-enabled/default-ssl.conf: No such file or directory
cp: cannot stat ‘/etc/QuickBox/setup/templates/fileshare.conf.template’: No such file or directory
sed: can't read /etc/php/7.0/fpm/php.ini: No such file or directory
sed: can't read /etc/php/7.0/apache2/php.ini: No such file or directory                                 [ DONE ]
Installing .rtorrent.rc for mythcry ... cp: cannot stat ‘/etc/QuickBox/setup/templates/rtorrent.rc.template’: No such file or directory
 [|]  sed: can't read /home/mythcry/.rtorrent.rc: No such file or directory
sed: can't read /home/mythcry/.rtorrent.rc: No such file or directory
sed: can't read /home/mythcry/.rtorrent.rc: No such file or directory                                   [ DONE ]
Adjusting fileupload & filemanager plugins ... rm: cannot remove ‘/srv/rutorrent/plugins/diskspace’: No such file or directory
 [|]  cp: cannot stat ‘/srv/rutorrent/home/fileshare/.htaccess’: No such file or directory
/root/QuickBox/setup/quickbox-setup: line 808: cd: /srv/rutorrent/home/fileshare/: No such file or directory
cp: cannot stat ‘/etc/QuickBox/setup/templates/rutorrent/plugins/fileshare/conf.php.template’: No such file or directory
sed: can't read /srv/rutorrent/plugins/filemanager/flm.class.php: No such file or directory
sed: can't read /srv/rutorrent/plugins/filemanager/settings.js.php: No such file or directory
sed: can't read /srv/rutorrent/plugins/filemanager/init.js: No such file or directory
/root/QuickBox/setup/quickbox-setup: line 817: cd: /srv/rutorrent/plugins/theme/themes/: No such file or directory                                                                                                     [|]  Can't open /srv/rutorrent/plugins/theme/conf.php: No such file or directory.                             [-]  chmod: cannot access ‘/srv/rutorrent/plugins/fileupload/scripts/upload’: No such file or directory
cp: cannot stat ‘/srv/rutorrent/plugins/fileupload/conf.php’: No such file or directory
find: `/srv/rutorrent/plugins/filemanager/scripts': No such file or directory                           [ DONE ]
Installing autodl-irssi ...  [|]  cp: cannot stat ‘autodl-irssi.pl’: No such file or directory          [ DONE ]
Making mythcry directory structure ... [ DONE ]
Writing mythcry rutorrent config.php file ... cp: cannot stat ‘/etc/QuickBox/setup/templates/rutorrent.users.config.template’: No such file or directory
 [|]  sed: can't read /srv/rutorrent/conf/users/mythcry/config.php: No such file or directory
sed: can't read /srv/rutorrent/conf/users/mythcry/config.php: No such file or directory
sed: can't read /srv/rutorrent/conf/users/mythcry/config.php: No such file or directory
sed: can't read /srv/rutorrent/conf/users/mythcry/config.php: No such file or directory
sed: can't read /srv/rutorrent/conf/users/mythcry/config.php: No such file or directory
sed: can't read /srv/rutorrent/conf/users/mythcry/config.php: No such file or directory                 [ DONE ]
Installing vsftpd ... [ DONE ]
Setting up vsftpd ...  [|]  cp: cannot stat ‘/etc/QuickBox/setup/templates/openssl.cnf.template’: No such file or directory
cp: cannot stat ‘/etc/QuickBox/setup/templates/vsftpd.conf.template’: No such file or directory         [ DONE ]
/root/QuickBox/setup/quickbox-setup: line 937: /srv/rutorrent/home/db/interface.txt: No such file or directory
/root/QuickBox/setup/quickbox-setup: line 938: /srv/rutorrent/home/db/master.txt: No such file or directory
sed: can't read /srv/rutorrent/home/inc/localize.php: No such file or directory
sed: can't read /srv/rutorrent/home/inc/localize.php: No such file or directory
rm: cannot remove '/srv/rutorrent/home/widgets/disk_datah.php': No such file or directory
cp: cannot stat '/etc/QuickBox/setup/templates/sysd/shellinabox.template': No such file or directory
cp: cannot stat '/etc/QuickBox/setup/templates/quickconsole/00_QuickConsole.css.template': No such file or directory
cp: cannot stat '/etc/QuickBox/setup/templates/web-console.conf.template': No such file or directory
sed: can't read /etc/apache2/sites-enabled/mythcry.console.conf: No such file or directory
sed: can't read /etc/apache2/sites-enabled/mythcry.console.conf: No such file or directory
chmod: cannot access '/etc/shellinabox/options-enabled/00_QuickConsole.css': No such file or directory
chmod: cannot access '/etc/shellinabox/options-enabled/00_QuickConsole.css': No such file or directory
Setting irssi/rtorrent to start on boot ... [ DONE ]
Setting permissions on mythcry ... [ DONE ]

**Comment by JMSDOnline** [comment]
There was an issue with the paths yesterday since we have moved the local install from /root/QuickBox to now /etc/QuickBox. However, I have just finished an install on Debian 8 for a user and there were no issues as the paths were addressed about 14 hours ago. If you like, please find me on the [QuickBox Plaza](https://plaza.quickbox.io) with a PM and I will look this over for you.
