### ISSUE TITLE
Menu link breaks with Deluge 1.3.14

### ISSUE THREAD

**Issue by d2dyno** [QuickBox/QuickBox#6]
I had (helped) quickbox install the latest version of Deluge. I noticed that now, the link to Deluge Web in the QB dashboard, is just a link to the QB dashboard.

**Comment by JMSDOnline** [comment]
I had seen this before and it had to do with the base url?

Is it passing the port attached to the url from the link? (ex. `http://MYSERVER:10729/`) Or is it specifying something different? This isn't a widely reported issue, but I have had a report on this once before a couple of months ago. Additionally, if you keep these issues to the forums we'll have a more solid foundation for support and future queries... I don't offer much support here on the Repositories.. but I **do** appreciate the report. :)

**Comment by d2dyno** [comment]
I'll check.

The forums aren't working for me. Everytime I login, I can't out cause I'm not logged in?

**Comment by JMSDOnline** [comment]
Are you attempting to login via https://quickbox.io/my-account/?

**Comment by d2dyno** [comment]
Got forums sorted. Visited from mobile and activated via email.

**Comment by d2dyno** [comment]
On a fresh server install with QB, upgrading by adding the PPA, then running upgrade command and rebooting, QB dashboard is working fine
