### ISSUE TITLE
Jackett installs, but does not properly run

### ISSUE THREAD

**Issue by d2dyno** [QuickBox/QuickBox#7]
When I install Jackett (either from web or box install jackett), it installs, but immidately is broken. The error I get in SSH is:
Installing jackett
chown: cannot access 'Jackett': No such file or directory
sed: can't read /home/user/.config/Jackett/ServerConfig.json: No such file or directory
sed: can't read /home/user/.config/Jackett/ServerConfig.json: No such file or directory

There are multiple reports of this on the QB forums.

**Comment by d2dyno** [comment]
Awesome @bohdan-s! That worked perfectly for me. I created a merge request for the fix you suggested.

**Comment by bohdan-s** [comment]
Thank you @d2dyno 
I was to lazy to to create a merge request :/
Just for the history, 
Original command returns:
`This repository
v0.7.1197`
Updated returns:
`v0.7.1197` 
The extra line was what was breaking the script.
