### ISSUE TITLE
BTSync doesn't open in Chrome

### ISSUE THREAD

**Issue by d2dyno** [QuickBox/QuickBox#8]
BTSync (Resilio), does not open in Chrome/56.0.2924.87. It can open just fine in Firefox however. Debug information was not written to the log for this, so I can't provide much logging details. This has been reported on the QB forums as well.

**Comment by JMSDOnline** [comment]
Not sure how much of this would be related to QuickBox as this is a reported issue to BTSync. You can check to see if this workaround posted at help.getsync.com helps:

[Sync Doesn't Start When Opening Link In Browser](https://help.getsync.com/hc/en-us/articles/204753649-Sync-doesn-t-start-when-opening-Link-in-browser)

**Comment by d2dyno** [comment]
Oddly enough, I did a fresh install on my seedbox (WAY too many issues for my sanity). Installed btsync via ssh and no longer have this issue.

My only thought right now, is maybe the issue came from having two ssl certs assigned to the same domain name (letsencrypt and btsync's built-in). I'll leave the issue open till I can test with LE.

**Comment by d2dyno** [comment]
Can confirm: issue returned after re-installing LetsEncrypt/certs

**Comment by d2dyno** [comment]
I have fixed this issue, with the following:

1. Copy the SSL key/cert.
```
sudo cat /etc/letsencrypt/live/DOMAIN/privkey.pem > /home/USER/.config/resilio-sync/private.key
sudo cat /etc/letsencrypt/live/DOMAIN/cert.pem > /home/USER/.config/resilio-sync/cert.pem
```
2. Edit the Resilio config.
`sudo nano /etc/resilio-sync/config.json`

3. Add this under "listen", within "webui"
```
"force_https" : true,
"ssl_certificate" : "/home/USER/.config/resilio-sync/cert.pem" ,
"ssl_private_key" : "/home/USER/.config/resilio-sync/private.key"
```

4. Add lines to post-renew script (from [here](https://quickbox.io/wiki/get-other-programs-on-quickbox-to-use-le-certs/))
```
echo "cat /etc/letsencrypt/live/DOMAIN/privkey.pem > /home/USER/.config/resilio-sync/private.key" >> /home/USER/le-post-hook.sh
echo "chmod 0644 /home/USER/.config/resilio-sync/private.key" >> /home/USER/le-post-hook.sh
echo "cat /etc/letsencrypt/live/DOMAIN/cert.pem > /home/USER/.config/resilio-sync/cert.pem" >> /home/USER/le-post-hook.sh
echo "chmod 0644 /home/USER/.config/resilio-sync/cert.pem" >> /home/USER/le-post-hook.sh
```

**Comment by JMSDOnline** [comment]
Thanks for the feedback @d2dyno. We'll add these steps to the wiki: [    Get other programs on QuickBox to use LE certs](https://quickbox.io/wiki/get-other-programs-on-quickbox-to-use-le-certs/)
